import { Sparkles, Heart, BookOpen, Code2, Dumbbell, Music, Palette } from "lucide-react";

export const FACTS = [
  {
    id: 1,
    title: "Software Engineer",
    fact: "I enjoy building fast, scalable, and intuitive web experiences with a strong focus on frontend engineering.",
    points: 100,
    color: "#20b2a6",
    shape: "heart",
    icon: Heart,
  },
  {
    id: 2,
    title: "Competitive Programmer",
    fact: "I like solving challenging problems and improving my coding skills.",
    points: 100,
    color: "#f5a623",
    shape: "oval",
    icon: Sparkles,
  },
  {
    id: 3,
    title: "I enjoy reading",
    fact: "I like reading to learn, relax, and get inspired by new ideas.",
    points: 100,
    color: "#7dd3fc",
    shape: "star",
    icon: BookOpen,
  },
  {
    id: 4,
    title: "I love coding",
    fact: "I enjoy building useful, interactive, and polished web experiences.",
    points: 100,
    color: "#a78bfa",
    shape: "teardrop",
    icon: Code2,
  },
  {
    id: 5,
    title: "about discipline and efforts",
    fact: "spend more than 40 hours a week practicing competitive programming and learning new technologies.",
    points: 100,
    color: "#34d399",
    shape: "diamond",
    icon: Dumbbell,
  },
  {
    id: 6,
    title: "I love music",
    fact: "Music helps me focus, relax, and stay creative.",
    points: 100,
    color: "#f472b6",
    shape: "oval",
    icon: Music,
  },
  {
    id: 7,
    title: "I enjoy designing",
    fact: "I like making clean layouts that feel modern and visually pleasing.",
    points: 100,
    color: "#fb7185",
    shape: "teardrop",
    icon: Palette,
  },
];